### ISSUE TITLE
Question about the e-money ecosystem in Japan

### ISSUE THREAD

**Issue by rTJ3** [treastrain/TRETJapanNFCReader#74]
Hi!

With the increased digitization and transfer of value, I'm trying to better understand how various platforms e-money "communicates" with another in Japan. For example, at a single pos terminal, a user can pay with multiple options: Suica, PayPay, LinePay, etc.

How do each of these options "play nice"? Are they separate protocols? Do they follow a single standard? Just encryption passing through nfc?

I apologize in advance for the basic question and if this is the wrong place to ask. I am just trying to learn and understand how these systems work.

Thanks for any help on this topic!

**Comment by treastrain** [comment]
Hello @rTJ3 . Thank you for asking me this question. Please note that the following is an answer to the best of my knowledge and may not be accurate.

In Japan, e-money services using various technologies are being developed. These include "FeliCa (NFC)" and "QR Code," for example.

Japan's transit e-money, such as Suica and PASMO, use "FeliCa" technology. Outside of Japan, Octopus in Hong Kong uses the same technology.

PayPay and LINE Pay, which you mention, primarily use "QR code" technology (technically, credit card payments using NFC-A/B or FeliCa(NFC-F) technology are also possible by registering a credit card issued by LINE Pay with Apple Pay or Google Pay). The same would be true for Alipay and others in mainland China.

For example, a store that accepts both Suica and PayPay payments would need to receive a declaration of the payment service the customer wishes to use and manually select it at the payment terminal.

> How do each of these options "play nice"? Are they separate protocols? Do they follow a single standard?

Sorry, this part I could not understand well. What exactly do you mean by "play nice"?

**Comment by rTJ3** [comment]
Hi @treastrain,

Thank you so much for the response! It actually clarifies my understanding quite a lot and, looking at the systems, the difference in tech is quite obvious, so thank you again.

By "play nice" I meant that with various platforms there could be conflicts between them. Ex. Platform A would conflict with Platform B, hence not "play nice" :) 

That said, I understand that the multiple platforms work independent of each other (They play nice!) , most likely, through unique identifiers and/or keys. 

So, with FeliCa tech and QR tech being separate approaches to e-money, is it possible to swap/transfer monetary value between them? For example, a user has ¥1000 on Suica card and would like to transfer the value to LINE Pay (or user has value on LINE Pay and would like to transfer it to Suica to use to pay for train).

To my understanding, currently, this function is unavailable, however would it be technically possible?

**Comment by treastrain** [comment]
@rTJ3 
I apologize that it has taken me an extremely long time to reply.

> So, with FeliCa tech and QR tech being separate approaches to e-money, is it possible to swap/transfer monetary value between them? For example, a user has ¥1000 on Suica card and would like to transfer the value to LINE Pay (or user has value on LINE Pay and would like to transfer it to Suica to use to pay for train).

I would like to clarify here that "FeliCa" and "QR code" are only a type of technology commonly used for payment.

In the case of Suica and LINE Pay, which you used as an example, there is no mutual transfer service of their respective balances because the operators providing both services are different.

LINE Pay, however, allows payments to be used with multiple technologies from a single balance in one location. That is Visa's PAN, Visa Contactless (NFC-A/B), iD (NFC-F a.k.a. FeliCa), and QR code/barcode. This is possible because it is a single business.

In addition, Suica supports the addition of SF with credit card payments. Visa credit cards can be used for this. Therefore, using Visa's PAN in LINE Pay, you can in effect transfer your balance to Suica.

However, as far as I know, there is no service that allows Suica payments to add balances to other e-money services.
